//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebarPosCommands.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DrawBOQ_HideMissing {
            get {
                return ((bool)(this["DrawBOQ_HideMissing"]));
            }
            set {
                this["DrawBOQ_HideMissing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public double DrawBOQ_TextHeight {
            get {
                return ((double)(this["DrawBOQ_TextHeight"]));
            }
            set {
                this["DrawBOQ_TextHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DrawBOQ_DisplayUnit {
            get {
                return ((int)(this["DrawBOQ_DisplayUnit"]));
            }
            set {
                this["DrawBOQ_DisplayUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DrawBOQ_Precision {
            get {
                return ((int)(this["DrawBOQ_Precision"]));
            }
            set {
                this["DrawBOQ_Precision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DrawBOQ_DrawShapes {
            get {
                return ((bool)(this["DrawBOQ_DrawShapes"]));
            }
            set {
                this["DrawBOQ_DrawShapes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DrawBOQ_HideUnusedDiameters {
            get {
                return ((bool)(this["DrawBOQ_HideUnusedDiameters"]));
            }
            set {
                this["DrawBOQ_HideUnusedDiameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TR EN RU")]
        public string DrawBOQ_LanguageOrder {
            get {
                return ((string)(this["DrawBOQ_LanguageOrder"]));
            }
            set {
                this["DrawBOQ_LanguageOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TR")]
        public string DrawBOQ_SelectedLanguages {
            get {
                return ((string)(this["DrawBOQ_SelectedLanguages"]));
            }
            set {
                this["DrawBOQ_SelectedLanguages"] = value;
            }
        }
    }
}
