//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCOM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Command_LEVEL_DrawingUnit {
            get {
                return ((int)(this["Command_LEVEL_DrawingUnit"]));
            }
            set {
                this["Command_LEVEL_DrawingUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Command_LEVEL_Precision {
            get {
                return ((int)(this["Command_LEVEL_Precision"]));
            }
            set {
                this["Command_LEVEL_Precision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LEVEL")]
        public string Command_LEVEL_BlockName {
            get {
                return ((string)(this["Command_LEVEL_BlockName"]));
            }
            set {
                this["Command_LEVEL_BlockName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Command_LEVEL_BlockScale {
            get {
                return ((double)(this["Command_LEVEL_BlockScale"]));
            }
            set {
                this["Command_LEVEL_BlockScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Command_LEVEL_BaseLevel {
            get {
                return ((double)(this["Command_LEVEL_BaseLevel"]));
            }
            set {
                this["Command_LEVEL_BaseLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Command_NUMARALANDIR_SelectObjects {
            get {
                return ((int)(this["Command_NUMARALANDIR_SelectObjects"]));
            }
            set {
                this["Command_NUMARALANDIR_SelectObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Command_NUMARALANDIR_AttributeName {
            get {
                return ((string)(this["Command_NUMARALANDIR_AttributeName"]));
            }
            set {
                this["Command_NUMARALANDIR_AttributeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Command_NUMARALANDIR_Order {
            get {
                return ((int)(this["Command_NUMARALANDIR_Order"]));
            }
            set {
                this["Command_NUMARALANDIR_Order"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Command_NUMARALANDIR_Prefix {
            get {
                return ((string)(this["Command_NUMARALANDIR_Prefix"]));
            }
            set {
                this["Command_NUMARALANDIR_Prefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Command_NUMARALANDIR_StartNumber {
            get {
                return ((int)(this["Command_NUMARALANDIR_StartNumber"]));
            }
            set {
                this["Command_NUMARALANDIR_StartNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Command_NUMARALANDIR_Increment {
            get {
                return ((int)(this["Command_NUMARALANDIR_Increment"]));
            }
            set {
                this["Command_NUMARALANDIR_Increment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Command_NUMARALANDIR_Digits {
            get {
                return ((int)(this["Command_NUMARALANDIR_Digits"]));
            }
            set {
                this["Command_NUMARALANDIR_Digits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Command_NUMARALANDIR_Suffix {
            get {
                return ((string)(this["Command_NUMARALANDIR_Suffix"]));
            }
            set {
                this["Command_NUMARALANDIR_Suffix"] = value;
            }
        }
    }
}
