//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCOM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Command_LEVEL_DrawingUnit {
            get {
                return ((int)(this["Command_LEVEL_DrawingUnit"]));
            }
            set {
                this["Command_LEVEL_DrawingUnit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Command_LEVEL_Precision {
            get {
                return ((int)(this["Command_LEVEL_Precision"]));
            }
            set {
                this["Command_LEVEL_Precision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LEVEL")]
        public string Command_LEVEL_BlockName {
            get {
                return ((string)(this["Command_LEVEL_BlockName"]));
            }
            set {
                this["Command_LEVEL_BlockName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Command_LEVEL_BlockScale {
            get {
                return ((double)(this["Command_LEVEL_BlockScale"]));
            }
            set {
                this["Command_LEVEL_BlockScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Command_LEVEL_BaseLevel {
            get {
                return ((double)(this["Command_LEVEL_BaseLevel"]));
            }
            set {
                this["Command_LEVEL_BaseLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Command_NUMARALANDIR_SelectObjects {
            get {
                return ((int)(this["Command_NUMARALANDIR_SelectObjects"]));
            }
            set {
                this["Command_NUMARALANDIR_SelectObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Command_NUMARALANDIR_AttributeName {
            get {
                return ((string)(this["Command_NUMARALANDIR_AttributeName"]));
            }
            set {
                this["Command_NUMARALANDIR_AttributeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Command_NUMARALANDIR_Order {
            get {
                return ((int)(this["Command_NUMARALANDIR_Order"]));
            }
            set {
                this["Command_NUMARALANDIR_Order"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Command_NUMARALANDIR_Prefix {
            get {
                return ((string)(this["Command_NUMARALANDIR_Prefix"]));
            }
            set {
                this["Command_NUMARALANDIR_Prefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Command_NUMARALANDIR_StartNumber {
            get {
                return ((double)(this["Command_NUMARALANDIR_StartNumber"]));
            }
            set {
                this["Command_NUMARALANDIR_StartNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Command_NUMARALANDIR_Increment {
            get {
                return ((double)(this["Command_NUMARALANDIR_Increment"]));
            }
            set {
                this["Command_NUMARALANDIR_Increment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Command_NUMARALANDIR_Suffix {
            get {
                return ((string)(this["Command_NUMARALANDIR_Suffix"]));
            }
            set {
                this["Command_NUMARALANDIR_Suffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Command_KMYAZ_TextHeight {
            get {
                return ((double)(this["Command_KMYAZ_TextHeight"]));
            }
            set {
                this["Command_KMYAZ_TextHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Command_KMYAZ_Precision {
            get {
                return ((int)(this["Command_KMYAZ_Precision"]));
            }
            set {
                this["Command_KMYAZ_Precision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KM: ")]
        public string Command_KMYAZ_Prefix {
            get {
                return ((string)(this["Command_KMYAZ_Prefix"]));
            }
            set {
                this["Command_KMYAZ_Prefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Command_KMYAZ_Interval {
            get {
                return ((double)(this["Command_KMYAZ_Interval"]));
            }
            set {
                this["Command_KMYAZ_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Command_NUMARALANDIR_Format {
            get {
                return ((string)(this["Command_NUMARALANDIR_Format"]));
            }
            set {
                this["Command_NUMARALANDIR_Format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Command_COORDGRID_TextHeight {
            get {
                return ((double)(this["Command_COORDGRID_TextHeight"]));
            }
            set {
                this["Command_COORDGRID_TextHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Command_COORDGRID_Interval {
            get {
                return ((int)(this["Command_COORDGRID_Interval"]));
            }
            set {
                this["Command_COORDGRID_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Command_LEVEL_Multiplier {
            get {
                return ((double)(this["Command_LEVEL_Multiplier"]));
            }
            set {
                this["Command_LEVEL_Multiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Command_PRINTENTCOORDS_SelectPoint {
            get {
                return ((bool)(this["Command_PRINTENTCOORDS_SelectPoint"]));
            }
            set {
                this["Command_PRINTENTCOORDS_SelectPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Command_PRINTENTCOORDS_SelectLine {
            get {
                return ((bool)(this["Command_PRINTENTCOORDS_SelectLine"]));
            }
            set {
                this["Command_PRINTENTCOORDS_SelectLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Command_PRINTENTCOORDS_SelectCircle {
            get {
                return ((bool)(this["Command_PRINTENTCOORDS_SelectCircle"]));
            }
            set {
                this["Command_PRINTENTCOORDS_SelectCircle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Command_PRINTENTCOORDS_SelectPolyline {
            get {
                return ((bool)(this["Command_PRINTENTCOORDS_SelectPolyline"]));
            }
            set {
                this["Command_PRINTENTCOORDS_SelectPolyline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Command_PRINTENTCOORDS_Select3DFace {
            get {
                return ((bool)(this["Command_PRINTENTCOORDS_Select3DFace"]));
            }
            set {
                this["Command_PRINTENTCOORDS_Select3DFace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Command_PRINTENTCOORDS_SelectText {
            get {
                return ((bool)(this["Command_PRINTENTCOORDS_SelectText"]));
            }
            set {
                this["Command_PRINTENTCOORDS_SelectText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[#]\t[X1]\t[Y2]\t[X2]\t[Y2]")]
        public string Command_PRINTENTCOORDS_LineFormat {
            get {
                return ((string)(this["Command_PRINTENTCOORDS_LineFormat"]));
            }
            set {
                this["Command_PRINTENTCOORDS_LineFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Command_PRINTENTCOORDS_Precision {
            get {
                return ((int)(this["Command_PRINTENTCOORDS_Precision"]));
            }
            set {
                this["Command_PRINTENTCOORDS_Precision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Command_PRINTENTCOORDS_UCS {
            get {
                return ((bool)(this["Command_PRINTENTCOORDS_UCS"]));
            }
            set {
                this["Command_PRINTENTCOORDS_UCS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Command_PRINTENTCOORDS_SelectBlock {
            get {
                return ((bool)(this["Command_PRINTENTCOORDS_SelectBlock"]));
            }
            set {
                this["Command_PRINTENTCOORDS_SelectBlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Command_DRAWAXES_DrawOnlyLine {
            get {
                return ((bool)(this["Command_DRAWAXES_DrawOnlyLine"]));
            }
            set {
                this["Command_DRAWAXES_DrawOnlyLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Command_DRAWAXES_BlockName {
            get {
                return ((string)(this["Command_DRAWAXES_BlockName"]));
            }
            set {
                this["Command_DRAWAXES_BlockName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Command_DRAWAXES_TextHeight {
            get {
                return ((double)(this["Command_DRAWAXES_TextHeight"]));
            }
            set {
                this["Command_DRAWAXES_TextHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Command_DRAWAXES_Precision {
            get {
                return ((int)(this["Command_DRAWAXES_Precision"]));
            }
            set {
                this["Command_DRAWAXES_Precision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public string Command_DRAWAXES_TextStyleName {
            get {
                return ((string)(this["Command_DRAWAXES_TextStyleName"]));
            }
            set {
                this["Command_DRAWAXES_TextStyleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AKS")]
        public string Command_DRAWAXES_AxisAttribute {
            get {
                return ((string)(this["Command_DRAWAXES_AxisAttribute"]));
            }
            set {
                this["Command_DRAWAXES_AxisAttribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KM")]
        public string Command_DRAWAXES_ChAttribute {
            get {
                return ((string)(this["Command_DRAWAXES_ChAttribute"]));
            }
            set {
                this["Command_DRAWAXES_ChAttribute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KM: ")]
        public string Command_DRAWAXES_ChPrefix {
            get {
                return ((string)(this["Command_DRAWAXES_ChPrefix"]));
            }
            set {
                this["Command_DRAWAXES_ChPrefix"] = value;
            }
        }
    }
}
